### ISSUE TITLE
Getting error while importing

### ISSUE THREAD

**Issue by damib** [Steffen-W/Import-LIB-KiCad-Plugin#1]
Hi I tried to follow your instruction but I got this error:
![image](https://user-images.githubusercontent.com/11184250/235087634-2631c6bb-4e64-4219-a887-27021f76fd4d.png)

No Idea while it is doing this.

**Comment by Steffen-W** [comment]
Hi @damib,

When importing, the plugin tries to import all zip files that are in your download folder. Apparently this does not work for any of the files.

For me it looks like that ESP32-DEVKITC-32U.zip comes from Snapeda. If this is true, please download the package as KiCad  **V4 & later** (you can select this in the download).

```
Import: /home/steffen/Downloads/ESP32-DEVKITC-32U.zip
Identify Snapeda
Import lib
Import 3d model
OK
```

The import process then works without errors for me. You only have to rotate the 3D model around the z-axis by -90. But that should not have been the problem for you. Try it, if it does not work, please contact me.

For XR21V1410 it looks to me like you have packed it into a zip file yourself. (maybe from https://www.snapeda.com/parts/XR21V1410IL16-F/MaxLinear,%20Inc./view-part/ )

I imported the following component instead:
https://componentsearchengine.com/part-view/XR21V1410IL16-F/MaxLinear%2C%20Inc.
This worked without any problems.

```
Import: /home/steffen/Downloads/LIB_XR21V1410IL16-F.zip
Identify Samacsys
Import lib
Import 3d model
OK
```

You can ignore messages like `'NoneType' object has no attribute 'exists'`, unless the file is a library to import. Maybe I will change the error message in the future, so that there will be no irritations.

Hopefully I could help you with this,
Regards Steffen
