### ISSUE TITLE
Default ports to "passive" instead of "unspecified"

### ISSUE THREAD

**Issue by Riesi-Inmox** [Steffen-W/Import-LIB-KiCad-Plugin#26]
When importing some components their IOs are set to "unspecified" which generates a lot of ERC errors.
It would probably make more sense to set ports to "passive" if the type is not clear.

For example this header will all be "unspecified":
https://www.digikey.at/de/models/1955705

Another issue is that the 3d model from the zip isn't assigned. I can create a second issue if you want.

Thanks for the great plugin!
Kind regards Riesi!

**Comment by Steffen-W** [comment]
Hi, I can fully understand your statement. Regarding the 3D file, the error is clearly with DigiKey. Have a look at the downloaded zip file and you will see that it is not there. But you can also download it directly from the provider, note the tick mark next to the 3d files.

![grafik](https://github.com/user-attachments/assets/7915d60c-7dd6-47cd-ac59-5c9f512ef33b)

I can also understand the part about the ports. However, I have decided not to change the port definitions. The components are imported without any changes. 

If I can help you with anything else, just write. I am shooting the issue as I do not recognise any errors.

**Comment by Riesi-Inmox** [comment]
Interesting that you dont get an STL. For me the zip has the 3d model:
![image](https://github.com/user-attachments/assets/c408214c-6061-423a-906b-63126278c251)

**Comment by Steffen-W** [comment]
Interesting, I did not have the file. The problem that is probably the case here is that I do not support digikey per se. For the supported platforms, I try to find out which platform it is via the data structure. So if you download it from the direct provider and not via digikey, it will work. However, I can adapt this so that digikey is also possible without any problems.
